# Training configuration
GPU: [0,1,2,3]

VERBOSE: False

MODEL:
  MODE: 'LOL_DPAG'      #Illum_YCRCB_Denoise_IN_w

# Optimization arguments.
OPTIM:
  BATCH: 16
  EPOCHS: 5000
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 1e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 128
  VAL_PS: 256
  TRAIN_DIR: ''       # path to training data
  VAL_DIR: '' # path to validation data
  SAVE_DIR: 'checkpoints_LOL'           # path to save models_v1 and images
